org.gradle.jvmargs=-Xmx8G -Dorg.gradle.logging.level=warn -Djava.util.concurrent.ForkJoinPool.common.parallelism=1
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.131
neo_version_range=[21.1.131,)
loader_version_range=[1,)

mod_id=immersivetechnology
mod_name=Immersive Technology
mod_license=LGPL-3.0
mod_version=2.0.1
mod_group_id=mctmods.immersivetechnology
mod_authors=tgstyle, MagneticPrism
mod_description=Immersive Technology for Minecraft 1.21.1 on NeoForge.
